version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_USERNAME=cassandra_user
      - CASSANDRA_PASSWORD=cassandra_password
    ports:
      - "9042:9042"
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
